pipeline:
  name: mar22
  identifier: mar22
  projectIdentifier: meenalocal
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: te
        identifier: te
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo exam
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
